version: "3.0"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - my-network
  
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    networks:
      - my-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  hook_kafka_producer:
      build: ./HookKafkaProducer
      image: hook_kafka_producer
      depends_on:
        - kafka
      ports:
        - 7158:7158
      networks:
        - my-network
  kafkaconsumer:
      image: kosts0/kafka_consumer
      depends_on:
        - kafka
      ports:
        - 8084:8084
      networks:
        - my-network
  runner_client:
      build: ./RunnerClient
      image: runner_client
      depends_on:
        - kafkaconsumer
      networks:
        - my-network
      deploy:
        mode: replicated
        replicas: 3
networks:
  my-network: